#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
# A SIGTERM signal doesn't stop it

while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM 
done
